FROM rust:nightly

# Install system dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    libasound2-dev

# Create a new empty shell project
RUN USER=root cargo new --bin app
WORKDIR /app

# Copy the manifests
COPY Cargo.toml Cargo.lock ./

# Build only the dependencies to cache them
RUN cargo build --release
RUN rm src/*.rs

# Copy the source code
COPY . .

# Build the project
RUN cargo build --release

# Run the binary
CMD ["./target/release/app"]