[build]
# Install necessary system packages
commands = [
    "apt-get update && apt-get install -y pkg-config libasound2-dev",
    "export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig",
    "cargo build --release"
]

[start]
# Command to run the built binary
command = "./target/release/app"