[target.x86_64-unknown-linux-gnu]
rustflags = [
  # LLD linker
  #
  # You may need to install it:
  #
  # - Ubuntu: `sudo apt-get install lld clang`
  # - Fedora: `sudo dnf install lld clang`
  # - Arch: `sudo pacman -S lld clang`
  "-Clink-arg=-fuse-ld=lld",

  # Nightly
  "-Zshare-generics=y",
  "-Zthreads=0",
]

[target.wasm32-unknown-unknown]
rustflags = [
  # Nightly
  "-Zshare-generics=y",
  "-Zthreads=0",
]
